# Generated by Django 3.2.3 on 2021-05-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_inquaryform_orderform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderform',
            old_name='contact_no',
            new_name='Qty',
        ),
        migrations.RenameField(
            model_name='orderform',
            old_name='email',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderform',
            old_name='name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='orderform',
            name='message',
        ),
        migrations.AddField(
            model_name='orderform',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderform',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
