# Generated by Django 3.2.3 on 2021-05-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_orderform_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderform',
            name='product',
            field=models.CharField(default='', max_length=20),
        ),
    ]
